#!/bin/bash

echo '\nAliases:'
echo '\tget-aliases\t- Get aliases list'
echo '\nPackage operations:'
echo '\tpackup\t- apt update and upgrade'
echo '\nFile operations:'
echo '\tll\t- List File'
echo '\tfi\t- File Manager'
echo '\nGit operations:'
echo '\tgs\t- git status'
echo '\tgb\t- git branch'
echo '\tgch\t- git checkout'
echo '\tgcha\t- git checkout -b'
echo '\tgchd\t- git checkout -D'
echo '\tgl\t- git log --oneline'
echo '\tgpl\t- git pull'
echo '\tgph\t- git push'
echo '\tga\t- git add'
echo '\tgc\t- git commit -m'
echo '\nDocker operations:'
echo '\tdc\t- docker-compose'
echo '\tdo\t- docker'
echo '\tdi\t- docker image ls -a'
echo '\tdirm\t- docker image rm -f'
echo '\tdip\t- docker image prune'
echo '\tdcon\t- docker container ls -a'
echo '\tdconrm\t- docker container rm -f'
echo '\tdconp\t- docker container prune'